### ISSUE TITLE
Release jar

### ISSUE THREAD

**Issue by Madis0** [liachmodded/brandpacket#2]
Could you upload a jar built for 1.14.4?

**Comment by liach** [comment]
@Madis0 In theory this jar should just work for 1.14.4. Does it not work for 1.14.4?

**Comment by Madis0** [comment]
Where is the jar? I only see the source...

**Comment by liach** [comment]
https://github.com/liachmodded/brandpacket/packages/40066 The jar here should work

**Comment by Madis0** [comment]
Got it, was looking for it in readme or releases.
