### ISSUE TITLE
brandpacket 0.0.2.1 breaks the ability to join both singeplayer and multiplayer worlds on Minecraft Version 1.20.2

### ISSUE THREAD

**Issue by UwUCatAgent** [liachmodded/brandpacket#8]
**Version Information:** 
brandpacket-0.0.2.1.jar [Taken from here](https://github.com/liachmodded/brandpacket/packages/40066)

**Log Information**
For singleplayer world [whoops singleplayer.txt](https://github.com/liachmodded/brandpacket/files/12839775/whoops.singleplayer.txt)
For multiplayer world [latest.log](https://github.com/liachmodded/brandpacket/files/12839757/latest.log)

**Fabric Loader Version**
0.14.22

**Java Version**
OpenJDK 20

**CPU**
Ryzen 7 5700U

**GPU**
Radeon Graphics (that came with the Ryzen 7 5700U)

**Additional Information**
I tested only with brandpacket to isolate this issue. This particular version of brandpacket has worked up all the way to version 1.20.1 with no supposed issues. Updating the minecraft version to 1.20.2 and attempting to join any world results in a disconnect. My suspicion is the networking changes that were added with 1.20.2

EDIT: Removed the auth token stuff in the singleplayer log whoops

**Comment by ghost** [comment]
After I installed Nochatreportc mod, I couldn't open it normally.
